all:
  children:
    localhost:
      hosts:
        localhost1:
          ansible_host: 127.0.0.1
          ansible_user: denis
          ansible_pass: 3087
          ansible_connection: local
          ansible_become_pass: 3087
    haproxy:
      hosts:
        haproxy1:
          ansible_host: ---------
    wordpress:
      hosts:
        wordpress1:
          ansible_host: 127.0.0.1
          ansible_port: 2203
        wordpress2:
          ansible_host: 127.0.0.1
          ansible_port: 2204
    database:
      hosts:
        mysql:
          ansible_host: 127.0.0.1
          ansible_port: 2202

