---
- hosts: localhost

  tasks:
    - name: install vagrant
      apt: pkg={{ item }} state=latest
      with_items:
        - vagrant
        
    - name: add VMs
      shell: |
        vagrant box add /home/denis/.vagrant.d/boxes/focal-server-cloudimg-amd64-vagrant.box  --name dz5
        cd /home/denis/.vagrant.d/boxes/dz5/
        vagrant init
        cp /home/denis/.vagrant.d/boxes/Vagrantfile /home/denis/.vagrant.d/boxes/dz5/Vagrantfile
        vagrant up
        vagrant ssh-config
      register: result
      ignore_errors: true
      
    - debug: var=result

- hosts: mysql
  become: true
  roles:
    - { role: geerlingguy.mysql, tags: [mysgl]}

- hosts: wordpress
  become: true
  vars_files:
    - /etc/ansible/vars/wordpress.yml
  roles:
    - { role: geerlingguy.nginx, tags: [nginx] }
    - { role: geerlingguy.php, tags: [php] }
    - { role: wordpress, tags: [wordpress] }

- hosts: haproxy
  become: true
  roles:
    - { role: geerlingguy.haproxy, tags: [haproxy]}
